/* The following code was generated by JFlex 1.7.0 */

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;
import java.util.Vector;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/LexicalAnalyzer.flex</tt>
 */
public class LexicalAnalyzer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int DECIMAL_SN = 2;
  public static final int C99_VAR = 4;
  public static final int REL_OPE = 6;
  public static final int CONDITION_STATEMENT = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  1,  1,  1,  1,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\12\0\1\7\1\7\1\7\1\7\32\0\1\21\1\22\1\25\1\24"+
    "\1\0\1\23\1\0\1\26\12\1\1\17\1\16\1\35\1\20\1\34"+
    "\2\0\2\2\1\3\13\2\1\4\13\2\6\0\1\43\1\10\1\5"+
    "\1\15\1\11\1\27\1\12\1\31\1\13\2\2\1\32\1\40\1\14"+
    "\1\6\1\42\1\2\1\37\1\33\1\30\2\2\1\36\1\2\1\41"+
    "\1\2\12\0\1\7\u1fa2\0\1\7\1\7\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\3\3\1\4\5\3\1\5\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\2\3"+
    "\1\15\1\16\6\3\1\17\2\3\1\20\1\3\1\21"+
    "\1\22\2\3\1\23\4\3\1\0\1\3\1\1\1\3"+
    "\1\24\1\3\1\25\1\26\5\3\1\0\4\3\1\27"+
    "\1\30\1\31\1\3\1\32\1\3\1\33\1\34\2\3"+
    "\1\35\1\36\1\37\2\3\1\40";

  private static int [] zzUnpackAction() {
    int [] result = new int[80];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\154\0\220\0\264\0\330\0\110"+
    "\0\374\0\u0120\0\u0144\0\u0168\0\u018c\0\110\0\u01b0\0\110"+
    "\0\110\0\110\0\110\0\110\0\110\0\110\0\u01d4\0\u01f8"+
    "\0\110\0\110\0\u021c\0\u0240\0\u0264\0\u0288\0\u02ac\0\u02d0"+
    "\0\220\0\u02f4\0\u0318\0\220\0\u033c\0\220\0\110\0\u0360"+
    "\0\u0384\0\220\0\u03a8\0\u03cc\0\u03f0\0\u0414\0\u0438\0\u045c"+
    "\0\u0480\0\u04a4\0\u04c8\0\u04ec\0\220\0\220\0\u0510\0\u0534"+
    "\0\u0558\0\u057c\0\u05a0\0\u05c4\0\u05e8\0\u060c\0\u0630\0\u0654"+
    "\0\220\0\220\0\220\0\u0678\0\220\0\u069c\0\220\0\220"+
    "\0\u06c0\0\u06e4\0\220\0\220\0\220\0\u0708\0\u072c\0\220";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[80];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\5\1\7\1\5\1\10"+
    "\1\11\1\12\1\5\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\3\5\1\31\1\32\1\33\1\34\2\5\1\35"+
    "\1\5\44\10\45\0\1\4\43\0\6\5\1\0\6\5"+
    "\11\0\5\5\2\0\6\5\1\0\3\5\1\36\2\5"+
    "\1\0\6\5\11\0\5\5\2\0\6\5\1\0\5\5"+
    "\1\37\1\0\6\5\11\0\5\5\2\0\6\5\1\0"+
    "\6\5\1\0\1\5\1\40\4\5\11\0\5\5\2\0"+
    "\3\5\1\41\2\5\1\0\6\5\1\0\4\5\1\42"+
    "\1\5\11\0\3\5\1\43\1\5\2\0\6\5\1\0"+
    "\6\5\1\0\6\5\11\0\1\44\4\5\2\0\6\5"+
    "\1\0\5\5\1\45\1\0\6\5\11\0\5\5\2\0"+
    "\6\5\1\0\5\5\1\46\1\0\6\5\11\0\5\5"+
    "\2\0\6\5\20\0\1\47\24\0\5\5\1\50\1\0"+
    "\6\5\11\0\5\5\2\0\1\5\1\51\4\5\1\0"+
    "\5\5\1\52\1\0\6\5\11\0\2\5\1\53\2\5"+
    "\2\0\6\5\1\0\6\5\1\0\6\5\11\0\2\5"+
    "\1\54\2\5\2\0\6\5\1\0\6\5\1\0\1\5"+
    "\1\55\4\5\11\0\5\5\2\0\6\5\1\0\6\5"+
    "\1\0\6\5\11\0\5\5\2\0\1\5\1\56\4\5"+
    "\1\57\2\36\1\60\3\36\1\57\6\36\11\57\5\36"+
    "\2\57\6\36\1\61\6\37\1\0\6\37\11\61\5\37"+
    "\2\61\6\37\1\0\6\5\1\0\2\5\1\62\3\5"+
    "\11\0\5\5\2\0\6\5\1\0\6\5\1\0\5\5"+
    "\1\63\11\0\5\5\2\0\6\5\1\0\6\5\1\0"+
    "\6\5\11\0\4\5\1\64\2\0\6\5\1\0\6\5"+
    "\1\0\6\5\11\0\1\5\1\65\3\5\2\0\6\5"+
    "\1\0\6\5\1\0\6\5\11\0\5\5\2\0\1\5"+
    "\1\66\4\5\1\0\5\5\1\67\1\0\6\5\11\0"+
    "\5\5\2\0\6\5\1\0\6\5\1\0\1\5\1\70"+
    "\4\5\11\0\5\5\2\0\6\5\1\0\6\5\1\0"+
    "\3\5\1\71\2\5\11\0\5\5\2\0\6\5\1\0"+
    "\6\5\1\0\6\5\11\0\5\5\2\0\5\5\1\72"+
    "\1\0\6\5\1\0\3\5\1\73\2\5\11\0\5\5"+
    "\2\0\6\5\3\57\1\74\41\57\2\36\1\60\1\5"+
    "\2\36\1\57\6\36\11\57\5\36\2\57\6\36\7\61"+
    "\1\0\34\61\1\0\6\5\1\0\3\5\1\75\2\5"+
    "\11\0\5\5\2\0\6\5\1\0\6\5\1\0\3\5"+
    "\1\76\2\5\11\0\1\77\4\5\2\0\1\100\5\5"+
    "\1\0\6\5\1\0\1\5\1\101\4\5\11\0\5\5"+
    "\2\0\6\5\1\0\6\5\1\0\6\5\11\0\5\5"+
    "\2\0\2\5\1\102\3\5\1\0\6\5\1\0\4\5"+
    "\1\103\1\5\11\0\5\5\2\0\6\5\1\0\6\5"+
    "\1\0\6\5\11\0\3\5\1\104\1\5\2\0\6\5"+
    "\1\0\6\5\1\0\5\5\1\105\11\0\5\5\2\0"+
    "\6\5\1\0\6\5\1\0\4\5\1\106\1\5\11\0"+
    "\5\5\2\0\6\5\3\57\1\74\1\3\37\57\1\0"+
    "\6\5\1\0\4\5\1\107\1\5\11\0\5\5\2\0"+
    "\6\5\1\0\6\5\1\0\6\5\11\0\1\110\4\5"+
    "\2\0\6\5\1\0\5\5\1\111\1\0\6\5\11\0"+
    "\5\5\2\0\6\5\1\0\6\5\1\0\6\5\11\0"+
    "\2\5\1\112\2\5\2\0\6\5\1\0\6\5\1\0"+
    "\1\5\1\113\4\5\11\0\5\5\2\0\6\5\1\0"+
    "\6\5\1\0\6\5\11\0\1\5\1\114\3\5\2\0"+
    "\6\5\1\0\6\5\1\0\6\5\11\0\5\5\2\0"+
    "\1\5\1\115\4\5\1\0\6\5\1\0\3\5\1\116"+
    "\2\5\11\0\5\5\2\0\6\5\1\0\6\5\1\0"+
    "\6\5\11\0\3\5\1\117\1\5\2\0\6\5\1\0"+
    "\6\5\1\0\1\5\1\120\4\5\11\0\5\5\2\0"+
    "\6\5";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1872];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\4\1\1\11\5\1\1\11\1\1\7\11"+
    "\2\1\2\11\14\1\1\11\7\1\1\0\14\1\1\0"+
    "\24\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[80];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */


    private java.util.Map<String, Integer> symbolTable = new TreeMap<>();
        private Vector<Symbol> symbols = new Vector<>();

            public java.util.Map<String, Integer> getSymbolTable(){
                return this.symbolTable;
            }

            public java.util.Vector<Symbol> getSymbols(){
                return this.symbols;
            }

            private Symbol addToSymbolsStructures(LexicalUnit lexicalUnit){
                Symbol symbol = new Symbol(lexicalUnit, yyline, yycolumn, yytext());
                if (symbol.getType() == LexicalUnit.VARNAME) {
                    symbolTable.compute(symbol.getValue().toString(), (k, v) -> (v == null) ? 1 : v + 1);
                }
                symbols.add(symbol);
                return symbol;

            }

            private Symbol endOfFile(){
                Symbol symbol = new Symbol(LexicalUnit.END_OF_STREAM, yyline, yycolumn);
                symbols.add(symbol);
                return symbol;
            }





  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexicalAnalyzer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 146) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { 	return endOfFile();
    //return new Symbol(LexicalUnit.END_OF_STREAM, yyline, yycolumn);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { 
            } 
            // fall through
          case 33: break;
          case 2: 
            { addToSymbolsStructures(LexicalUnit.NUMBER);
            } 
            // fall through
          case 34: break;
          case 3: 
            { addToSymbolsStructures(LexicalUnit.VARNAME);
            } 
            // fall through
          case 35: break;
          case 4: 
            { System.out.print(yytext());
            } 
            // fall through
          case 36: break;
          case 5: 
            { addToSymbolsStructures(LexicalUnit.SEMICOLON);
            } 
            // fall through
          case 37: break;
          case 6: 
            { addToSymbolsStructures(LexicalUnit.EQUAL);
            } 
            // fall through
          case 38: break;
          case 7: 
            { addToSymbolsStructures(LexicalUnit.LPAREN);
            } 
            // fall through
          case 39: break;
          case 8: 
            { addToSymbolsStructures(LexicalUnit.RPAREN);
            } 
            // fall through
          case 40: break;
          case 9: 
            { addToSymbolsStructures(LexicalUnit.MINUS);
            } 
            // fall through
          case 41: break;
          case 10: 
            { addToSymbolsStructures(LexicalUnit.PLUS);
            } 
            // fall through
          case 42: break;
          case 11: 
            { addToSymbolsStructures(LexicalUnit.TIMES);
            } 
            // fall through
          case 43: break;
          case 12: 
            { addToSymbolsStructures(LexicalUnit.DIVIDE);
            } 
            // fall through
          case 44: break;
          case 13: 
            { addToSymbolsStructures(LexicalUnit.GREATER);
            } 
            // fall through
          case 45: break;
          case 14: 
            { addToSymbolsStructures(LexicalUnit.SMALLER);
            } 
            // fall through
          case 46: break;
          case 15: 
            { addToSymbolsStructures(LexicalUnit.BY);
            } 
            // fall through
          case 47: break;
          case 16: 
            { addToSymbolsStructures(LexicalUnit.IF);
            } 
            // fall through
          case 48: break;
          case 17: 
            { addToSymbolsStructures(LexicalUnit.DO);
            } 
            // fall through
          case 49: break;
          case 18: 
            { addToSymbolsStructures(LexicalUnit.ASSIGN);
            } 
            // fall through
          case 50: break;
          case 19: 
            { addToSymbolsStructures(LexicalUnit.TO);
            } 
            // fall through
          case 51: break;
          case 20: 
            { addToSymbolsStructures(LexicalUnit.END);
            } 
            // fall through
          case 52: break;
          case 21: 
            { addToSymbolsStructures(LexicalUnit.NOT);
            } 
            // fall through
          case 53: break;
          case 22: 
            { addToSymbolsStructures(LexicalUnit.FOR);
            } 
            // fall through
          case 54: break;
          case 23: 
            { addToSymbolsStructures(LexicalUnit.ELSE);
            } 
            // fall through
          case 55: break;
          case 24: 
            { addToSymbolsStructures(LexicalUnit.FROM);
            } 
            // fall through
          case 56: break;
          case 25: 
            { addToSymbolsStructures(LexicalUnit.THEN);
            } 
            // fall through
          case 57: break;
          case 26: 
            { addToSymbolsStructures(LexicalUnit.READ);
            } 
            // fall through
          case 58: break;
          case 27: 
            { addToSymbolsStructures(LexicalUnit.BEG);
            } 
            // fall through
          case 59: break;
          case 28: 
            { addToSymbolsStructures(LexicalUnit.ENDIF);
            } 
            // fall through
          case 60: break;
          case 29: 
            { addToSymbolsStructures(LexicalUnit.WHILE);
            } 
            // fall through
          case 61: break;
          case 30: 
            { addToSymbolsStructures(LexicalUnit.PRINT);
            } 
            // fall through
          case 62: break;
          case 31: 
            { addToSymbolsStructures(LexicalUnit.ENDFOR);
            } 
            // fall through
          case 63: break;
          case 32: 
            { addToSymbolsStructures(LexicalUnit.ENDWHILE);
            } 
            // fall through
          case 64: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java LexicalAnalyzer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        LexicalAnalyzer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new LexicalAnalyzer(reader);
          while ( !scanner.zzAtEOF ) scanner.nextToken();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
